definitions:
  domain.PaymentMethod:
    properties:
      maximumamount:
        type: number
      method_id:
        type: integer
      paymentmethod:
        type: string
    type: object
  domain.Users:
    properties:
      block_status:
        type: boolean
      email:
        maxLength: 12
        minLength: 3
        type: string
      name:
        maxLength: 12
        minLength: 3
        type: string
      password:
        maxLength: 64
        minLength: 8
        type: string
      phone:
        maxLength: 10
        minLength: 10
        type: string
      user_Id:
        type: integer
      username:
        maxLength: 12
        minLength: 3
        type: string
      verification:
        type: boolean
    required:
    - email
    - name
    - password
    - phone
    - username
    type: object
  req.LoginStruct:
    properties:
      password:
        maxLength: 64
        minLength: 8
        type: string
      username:
        maxLength: 12
        minLength: 3
        type: string
    required:
    - password
    - username
    type: object
  response.Response:
    properties:
      data: {}
      errors: {}
      message:
        type: string
      status_code:
        type: integer
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      description: Enter user_name  with password
      operationId: UserLogin
      parameters:
      - description: Input Field
        in: body
        name: inputs
        required: true
        schema:
          $ref: '#/definitions/req.LoginStruct'
      responses:
        "200":
          description: successfully logged in
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: invalid input
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: faild to generat JWT
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: api for user to login
      tags:
      - User Login
  /order/create:
    post:
      description: Enter address id and method id
      parameters:
      - description: address_id
        format: int32
        in: query
        name: page
        required: true
        type: integer
      - description: paymentmethod_id
        format: int32
        in: query
        name: pagesize
        required: true
        type: integer
      responses:
        "200":
          description: successfully  created order
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: failed to create order
          schema:
            $ref: '#/definitions/response.Response'
      summary: api for create order
      tags:
      - Create Order
  /paymentmethod/add:
    post:
      description: Enter payment method and maximum amount
      parameters:
      - description: Input Field
        in: body
        name: inputs
        required: true
        schema:
          $ref: '#/definitions/domain.PaymentMethod'
      responses:
        "200":
          description: successfully  added payment method
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: failed to add payment method
          schema:
            $ref: '#/definitions/response.Response'
      summary: api for add payment method by admin
      tags:
      - Add payment method
  /paymentmethod/delete:
    delete:
      description: Delete payment methods
      parameters:
      - description: id
        format: int32
        in: query
        name: page
        required: true
        type: integer
      responses:
        "200":
          description: successfully  deleted method
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: failed to delete method
          schema:
            $ref: '#/definitions/response.Response'
      summary: delete paymentmethod
      tags:
      - Delete Payment method
  /paymentmethod/update:
    patch:
      description: Enter payment method and maximum amount with id
      parameters:
      - description: Input Field
        in: body
        name: inputs
        required: true
        schema:
          $ref: '#/definitions/domain.PaymentMethod'
      responses:
        "200":
          description: successfully  updated payment method
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: failed to updatepayment method
          schema:
            $ref: '#/definitions/response.Response'
      summary: api for update payment method by admin
      tags:
      - upadate payment method
  /paymentmethod/view:
    get:
      description: Get all products
      parameters:
      - description: Page
        format: int32
        in: query
        name: page
        required: true
        type: integer
      - description: Page Size
        format: int32
        in: query
        name: pagesize
        required: true
        type: integer
      responses:
        "200":
          description: successfully  displayed all prioducts
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: ferror while getting data
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get all paymentmethods
      tags:
      - View all payment method
  /signup/loginorsignup:
    post:
      description: Enter phone number
      parameters:
      - description: Input Field
        in: body
        name: inputs
        required: true
        schema:
          $ref: '#/definitions/domain.Users'
      responses:
        "200":
          description: error while sending otp
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: otp send successfully
          schema:
            $ref: '#/definitions/response.Response'
      summary: api for user to send otp to phone
      tags:
      - add Phone Number
  /signup/verifyotp:
    post:
      description: Enter otp
      responses:
        "200":
          description: error while verifying otp
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: otp  successfully verified
          schema:
            $ref: '#/definitions/response.Response'
      summary: api for Verify otp of user
      tags:
      - OTP Verification
swagger: "2.0"
