// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"golang_project_ecommerce/pkg/api"
	"golang_project_ecommerce/pkg/api/handler"
	"golang_project_ecommerce/pkg/config"
	"golang_project_ecommerce/pkg/db"
	"golang_project_ecommerce/pkg/repository"
	"golang_project_ecommerce/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	userUsecase := usecase.NewUserUsecase(userRepository)
	userHandler := handler.NewUserhandler(userUsecase)
	serverHTTP := http.NewServerHTTP(userHandler)
	return serverHTTP, nil
}
